import "./globals.css";

import Navbar from "@/app/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        <div className="h-2 bg-white"></div>
        {children}
      </body>
    </html>
  );
}
